// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table internal header
//
// Internal details; most calling programs do not need this header,
// unless using verilator public meta comments.

#ifndef VERILATED_VTESTDRIVER__SYMS_H_
#define VERILATED_VTESTDRIVER__SYMS_H_  // guard

#include "verilated.h"

// INCLUDE MODEL CLASS

#include "VTestDriver.h"

// INCLUDE MODULE CLASSES
#include "VTestDriver___024root.h"
#include "VTestDriver___024unit.h"

// DPI TYPES for DPI Export callbacks (Internal use)

// SYMS CLASS (contains all model state)
class alignas(VL_CACHE_LINE_BYTES)VTestDriver__Syms final : public VerilatedSyms {
  public:
    // INTERNAL STATE
    VTestDriver* const __Vm_modelp;
    VlDeleter __Vm_deleter;
    bool __Vm_didInit = false;

    // MODULE INSTANCE STATE
    VTestDriver___024root          TOP;
    VTestDriver___024unit          TOP____024unit;

    // SCOPE NAMES
    VerilatedScope __Vscope_TestDriver;
    VerilatedScope __Vscope_TestDriver__testHarness;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__bank__fragmenter;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__cbus__atomics;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__cbus__coupler_to_bootrom__fragmenter;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__cbus__coupler_to_clint__fragmenter;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__cbus__coupler_to_debug__fragmenter;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__cbus__coupler_to_l2_ctrl__fragmenter;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__cbus__coupler_to_plic__fragmenter;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__cbus__in_xbar;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__cbus__out_xbar;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__chipyard_prcictrl_domain__fragmenter;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__chipyard_prcictrl_domain__fragmenter_1;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__chipyard_prcictrl_domain__xbar;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__coh_wrapper__cork;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__coh_wrapper__cork__pool;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__coh_wrapper__l2__inclusive_cache_bank_sched;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__coh_wrapper__l2__inclusive_cache_bank_sched__directory;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__coh_wrapper__l2__inclusive_cache_bank_sched__mshrs_0;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__coh_wrapper__l2__inclusive_cache_bank_sched__mshrs_1;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__coh_wrapper__l2__inclusive_cache_bank_sched__mshrs_2;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__coh_wrapper__l2__inclusive_cache_bank_sched__mshrs_3;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__coh_wrapper__l2__inclusive_cache_bank_sched__mshrs_4;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__coh_wrapper__l2__inclusive_cache_bank_sched__mshrs_5;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__coh_wrapper__l2__inclusive_cache_bank_sched__mshrs_6;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__coh_wrapper__l2__inclusive_cache_bank_sched__requests;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__coh_wrapper__l2__inclusive_cache_bank_sched__sinkA__putbuffer;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__coh_wrapper__l2__inclusive_cache_bank_sched__sinkC;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__coh_wrapper__l2__inclusive_cache_bank_sched__sinkC__putbuffer;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__coh_wrapper__l2__inclusive_cache_bank_sched__sinkD;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__coh_wrapper__l2__inclusive_cache_bank_sched__sourceB;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__coh_wrapper__l2__inclusive_cache_bank_sched__sourceC;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__coh_wrapper__l2__inclusive_cache_bank_sched__sourceD;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__dtm;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__dtm__dmiAccessChain;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__dtm__dtmInfoChain;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__dtm__tapIO_idcodeChain;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__fbus__fbus_xbar;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__mbus__coupler_to_memory_controller_port_named_axi4__axi4yank;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__mbus__coupler_to_memory_controller_port_named_axi4__tl2axi4;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__mbus__mbus_xbar;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__pbus__atomics;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__pbus__coupler_to_bootaddressreg__fragmenter;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__pbus__coupler_to_device_named_uart_0__fragmenter;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__pbus__out_xbar;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__plic_domain__plic;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__sbus__system_bus_xbar;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__tile_prci_domain__element_reset_domain_rockettile__core;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__tile_prci_domain__element_reset_domain_rockettile__core__PlusArgTimeout;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__tile_prci_domain__element_reset_domain_rockettile__core__csr;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__tile_prci_domain__element_reset_domain_rockettile__core__ibuf;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__tile_prci_domain__element_reset_domain_rockettile__dcIF;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__tile_prci_domain__element_reset_domain_rockettile__dcIF__replayq;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__tile_prci_domain__element_reset_domain_rockettile__dcache;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__tile_prci_domain__element_reset_domain_rockettile__fpuOpt;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__tile_prci_domain__element_reset_domain_rockettile__frontend;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__tile_prci_domain__element_reset_domain_rockettile__frontend__icache;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__tile_prci_domain__element_reset_domain_rockettile__frontend__tlb;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__tile_prci_domain__element_reset_domain_rockettile__ptw;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__tile_prci_domain__element_reset_domain_rockettile__tlMasterXbar;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__tlDM__dmInner__dmInner;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__tlDM__dmInner__dmInner__sb2tlOpt;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__tlDM__dmOuter__dmiBypass__error;
    VerilatedScope __Vscope_TestDriver__testHarness__chiptop0__system__tlDM__dmOuter__dmiXbar;
    VerilatedScope __Vscope_TestDriver__testHarness__ram__tsi2tl;
    VerilatedScope __Vscope_TestDriver__testHarness__uart_sim_0_uartno0;

    // SCOPE HIERARCHY
    VerilatedHierarchy __Vhier;

    // CONSTRUCTORS
    VTestDriver__Syms(VerilatedContext* contextp, const char* namep, VTestDriver* modelp);
    ~VTestDriver__Syms();

    // METHODS
    const char* name() { return TOP.name(); }
};

#endif  // guard
